### PR TITLE
Secure

### PR DESCRIPTION
**Pull request by aaronspring**
# Description
 See xskillscore issue, same as in climpred
Should be done for every branch

### CODE REVIEW

**Comment by aaronspring** [comment]
Tests fail bc numba import issue. Anderson fixed this in his climpred PR

**Review by bradyrx — APPROVED** [review]

**Comment by bradyrx** [comment]
@aaronspring , will this break the github actions? I had those in there to make sure they ran on the PR branch being added and not the master branch. I can see why it could be a security concern but this might break our CI system.

**Comment by bradyrx** [comment]
For instance, the numba fix probably isn't reflected here in this testing since those other lines were deleted from the CI

**Comment by aaronspring** [comment]
> @aaronspring , will this break the github actions? I had those in there to make sure they ran on the PR branch being added and not the master branch. I can see why it could be a security concern but this might break our CI system.

I looked into other projects. they setup CI similarly as we did but without the secrets. I think it might only break CI seen in the forked repo. CI in the main repo will still work.

**Comment by aaronspring** [comment]
> For instance, the numba fix probably isn't reflected here in this testing since those other lines were deleted from the CI

the good news is that py38 passes. so it is a versioning thing. in climpred adding the numba dev branch worked.

**Comment by aaronspring** [comment]
also you need to delete or fix old branches that have this secrets lines

**Pull request merged**
